#!/bin/bash
## Monitor galera cluster size

## Where the alert should be sent to
EMAIL="SENDTO"

## Check if MariaDB is running
mysql_status=`/usr/sbin/service mysql status|awk {'print $1'}`

hostname=`hostname`
error=`tail -100 /var/log/mysql.log`

SUBJECT1="ERROR: [$hostname] Galera Cluster Size is wrong!"
SUBJECT2="WARNING: [$hostname] Galera Cluster Size is wrong!"
SUBJECT3="DISASTER: [$hostname] Galera Cluster not running!"
CLUSTER1="DISASTER: [$hostname] Galera cluster lost quorum! Please inspect the service!"

EMAILMESSAGE="/tmp/emailmessage.txt"

if [[ $mysql_status == "SUCCESS!" ]]; then
## Monitor cluster size state
  cluster_size=`mysql -e "show status like 'wsrep_cluster_size'" | tail -1 | awk {'print $2'}`
  if [ $cluster_size -eq 1 ]; then
    echo "Cluster size: $cluster_size" > $EMAILMESSAGE
    echo "======================================================" >> $EMAILMESSAGE
    echo "Stopping mysql to prevent split-brain!" >> $EMAILMESSAGE
    echo "======================================================" >> $EMAILMESSAGE
    echo "Latest error: $error" >> $EMAILMESSAGE
    /bin/mail -s "$SUBJECT1" "$EMAIL" < $EMAILMESSAGE
    /etc/init.d/mysql stop                    # stop the mysql server to prevent split-brain
  elif [ $cluster_size -eq 2 ]; then
    echo "Cluster size: $cluster_size" > $EMAILMESSAGE
    echo "======================================================" >> $EMAILMESSAGE
    echo "Latest error: $error" >> $EMAILMESSAGE
    /bin/mail -s "$SUBJECT2" "$EMAIL" < $EMAILMESSAGE
  fi
## Monitor cluster status
  cluster_status=`mysql -e "show status like 'wsrep_cluster_status'" | tail -1 | awk {'print $2'}`
  if [[ $cluster_status != "Primary" ]]; then
    echo "Please start here: http://galeracluster.com/documentation-webpages/quorumreset.html" > $EMAILMESSAGE
    echo "Cluster size: $cluster_size" >> $EMAILMESSAGE
    echo "Cluster size status: $cluster_status" >> $EMAILMESSAGE
    echo "======================================================" >> $EMAILMESSAGE
    echo "Latest error: $error" >> $EMAILMESSAGE
    /bin/mail -s "$CLUSTER1" "$EMAIL" < $EMAILMESSAGE
  else
    exit 0
  fi
elif [[ $mysql_status == "ERROR!" ]]; then
  echo "Latest error: $error" > $EMAILMESSAGE
  /bin/mail -s "$SUBJECT3" "$EMAIL" < $EMAILMESSAGE
fi

