GRANT ALL PRIVILEGES ON *.* TO 'galerareplicator'@'localhost' IDENTIFIED BY 'GOESHERE' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'galerareplicator'@'NODE1' IDENTIFIED BY 'GOESHERE' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'galerareplicator'@'NODE2' IDENTIFIED BY 'GOESHERE' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'galerareplicator'@'NODE3' IDENTIFIED BY 'GOESHERE' WITH GRANT OPTION;
FLUSH PRIVILEGES;
